export const fullKeySet = [
	"Flow Duration",
	"Total Fwd Packets",
	"Total Backward Packets",
	"Fwd Packets Length Total",
	"Bwd Packets Length Total",
	"Fwd Packet Length Max",
	"Fwd Packet Length Min",
	"Fwd Packet Length Mean",
	"Fwd Packet Length Std",
	"Bwd Packet Length Max",
	"Bwd Packet Length Min",
	"Bwd Packet Length Mean",
	"Bwd Packet Length Std",
	"Flow Bytes/s",
	"Flow Packets/s",
	"Flow IAT Mean",
	"Flow IAT Std",
	"Flow IAT Max",
	"Flow IAT Min",
	"Fwd IAT Total",
	"Fwd IAT Mean",
	"Fwd IAT Std",
	"Fwd IAT Max",
	"Fwd IAT Min",
	"Bwd IAT Total",
	"Bwd IAT Mean",
	"Bwd IAT Std",
	"Bwd IAT Max",
	"Bwd IAT Min",
	"Fwd PSH Flags",
	"Fwd Header Length",
	"Bwd Header Length",
	"Fwd Packets/s",
	"Bwd Packets/s",
	"Packet Length Min",
	"Packet Length Max",
	"Packet Length Mean",
	"Packet Length Std",
	"Packet Length Variance",
	"SYN Flag Count",
	"RST Flag Count",
	"ACK Flag Count",
	"URG Flag Count",
	"CWE Flag Count",
	"Down/Up Ratio",
	"Avg Packet Size",
	"Avg Fwd Segment Size",
	"Avg Bwd Segment Size",
	"Subflow Fwd Packets",
	"Subflow Fwd Bytes",
	"Subflow Bwd Packets",
	"Subflow Bwd Bytes",
	"Init Fwd Win Bytes",
	"Init Bwd Win Bytes",
	"Fwd Act Data Packets",
	"Fwd Seg Size Min",
	"Active Mean",
	"Active Std",
	"Active Max",
	"Active Min",
	"Idle Mean",
	"Idle Std",
	"Idle Max",
	"Idle Min",
	"Protocol",
];

export const onlyImportantKeySet = [
	"Protocol",
	"Idle Max",
	"Flow IAT Max",
	"Flow Duration",
	"Fwd IAT Max",
	"Fwd IAT Total",
	"Idle Mean",
	"ACK Flag Count",
	"Fwd IAT Std",
	"Fwd Packet Length Mean",
	"Avg Fwd Segment Size",
	"Packet Length Min",
	"Fwd Packet Length Min",
	"Idle Min",
	"Flow IAT Std",
	"Packet Length Mean",
	"Fwd IAT Mean",
	"Avg Packet Size",
	"Bwd IAT Max",
	"Bwd IAT Total",
	"Flow IAT Mean",
	"Fwd Packet Length Max",
	"Bwd IAT Std",
	"Packet Length Max",
	"Idle Std",
	"Bwd Packet Length Max",
	"Bwd IAT Mean",
	"Bwd Packet Length Std",
	"Packet Length Std",
	"Init Fwd Win Bytes",
	"Avg Bwd Segment Size",
	"Bwd Packet Length Mean",
	"Down/Up Ratio",
	"Active Max",
	"Fwd Packet Length Std",
	"URG Flag Count",
	"Flow Bytes/s",
	"Packet Length Variance",
	"Active Mean",
	"Active Std",
	"Subflow Bwd Packets",
	"Total Backward Packets",
	"Flow Packets/s",
	"Fwd Packets/s",
	"Fwd Act Data Packets",
	"CWE Flag Count",
	"Subflow Bwd Bytes",
	"Bwd Packets Length Total",
	"Subflow Fwd Bytes",
	"Fwd Packets Length Total",
	"Bwd Packet Length Min",
	"Fwd PSH Flags",
	"RST Flag Count",
	"Active Min",
	"Init Bwd Win Bytes",
	"Bwd IAT Min",
	"Fwd Seg Size Min",
	"Total Fwd Packets",
	"Subflow Fwd Packets",
];
